
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.chpp.grammar;

/** CUP generated class containing symbol constants. */
public class ParserSym {
  /* terminals */
  public static final int LKEY = 31;
  public static final int VBOL = 37;
  public static final int MULT = 18;
  public static final int CONST = 5;
  public static final int LSKEY = 33;
  public static final int LPAREN = 29;
  public static final int INT = 7;
  public static final int OUT = 20;
  public static final int ININT = 21;
  public static final int MINUS = 17;
  public static final int RPAREN = 30;
  public static final int SEMICOLON = 27;
  public static final int AND = 14;
  public static final int LT = 25;
  public static final int OR = 15;
  public static final int COMMA = 28;
  public static final int DIV = 19;
  public static final int BEGIN = 2;
  public static final int LOOP = 13;
  public static final int PLUS = 16;
  public static final int MAIN = 3;
  public static final int IF = 11;
  public static final int ID = 36;
  public static final int EOF = 0;
  public static final int RSKEY = 34;
  public static final int RETURN = 6;
  public static final int EQUAL = 23;
  public static final int RKEY = 32;
  public static final int error = 1;
  public static final int NUMBER = 35;
  public static final int VOID = 10;
  public static final int TUP = 9;
  public static final int WHILE = 12;
  public static final int BOL = 8;
  public static final int INBOL = 22;
  public static final int REQUAL = 24;
  public static final int GT = 26;
  public static final int ALPHA = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "BEGIN",
  "MAIN",
  "ALPHA",
  "CONST",
  "RETURN",
  "INT",
  "BOL",
  "TUP",
  "VOID",
  "IF",
  "WHILE",
  "LOOP",
  "AND",
  "OR",
  "PLUS",
  "MINUS",
  "MULT",
  "DIV",
  "OUT",
  "ININT",
  "INBOL",
  "EQUAL",
  "REQUAL",
  "LT",
  "GT",
  "SEMICOLON",
  "COMMA",
  "LPAREN",
  "RPAREN",
  "LKEY",
  "RKEY",
  "LSKEY",
  "RSKEY",
  "NUMBER",
  "ID",
  "VBOL"
  };
}

